// Custom Worker entrypoint.
//
// OpenNext's generated worker (`.open-next/worker.js`) only exports a `fetch`
// handler. Cloudflare Cron Triggers invoke `scheduled()`, so without this
// wrapper the trigger in wrangler.jsonc would be dropped on the floor and the
// delivery queue would never be worked — retries would exist in the code and
// never happen in production, which is a worse state than not having them.
//
// `main` in wrangler.jsonc points here rather than at the generated worker.
// See https://opennext.js.org/cloudflare/howtos/custom-worker

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";

type CronEnv = {
  DROP_CRON_SECRET?: string;
  NEXT_PUBLIC_SITE_URL?: string;
  WORKER_SELF_REFERENCE: {
    fetch(input: string, init?: RequestInit): Promise<Response>;
  };
};

type ScheduledController = { cron: string; scheduledTime: number };
type ExecutionContextLike = { waitUntil(promise: Promise<unknown>): void };

const FULFIL_PATH = "/api/cron/fulfil";

/** Bounded so a hung request cannot hold the invocation open to its limit. */
const BUDGET_MS = 25_000;

const worker = {
  fetch: handler.fetch,

  async scheduled(
    _controller: ScheduledController,
    env: CronEnv,
    ctx: ExecutionContextLike,
  ): Promise<void> {
    const origin = env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") || "https://drop.beaam.app";

    // The route refuses without this, by design: retries are a finite resource
    // and an open sweep lets anyone exhaust every pending delivery.
    if (!env.DROP_CRON_SECRET) {
      console.error("[cron] DROP_CRON_SECRET is not set — the fulfilment sweep cannot run.");
      return;
    }

    ctx.waitUntil(
      Promise.race([
        (async () => {
          try {
            const res = await env.WORKER_SELF_REFERENCE.fetch(`${origin}${FULFIL_PATH}`, {
              headers: { authorization: `Bearer ${env.DROP_CRON_SECRET}` },
            });
            const body = await res.text();
            // What it did, not that it ran. A sweep that reports nothing is
            // indistinguishable from one that never fired, which is the class
            // of silence this whole application argues against.
            if (!res.ok) {
              console.error(`[cron] fulfil returned ${res.status}: ${body.slice(0, 200)}`);
              return;
            }
            console.log(`[cron] fulfil ${body.slice(0, 200)}`);
          } catch (error) {
            console.error(
              `[cron] fulfil threw: ${error instanceof Error ? error.message : String(error)}`,
            );
          }
        })(),
        new Promise((resolve) =>
          setTimeout(() => {
            console.warn(`[cron] fulfil exceeded ${BUDGET_MS}ms — giving up this tick`);
            resolve(undefined);
          }, BUDGET_MS),
        ),
      ]),
    );
  },
};

export default worker;
